   (Be sure to include the period at the beginning!)

---

## 2. Paste the Workflow Code

3. In the large text area below the filename, **paste this code**:

   ```yaml name=.github/workflows/spellcheck.yml
   name: Spell Check

   on:
     push:
       branches: [ main ]
     pull_request:
       branches: [ main ]

   jobs:
     spellcheck:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v4
         - uses: rojopolis/spellcheck-github-actions@v0
